name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      # TODO cache

      - name: Install Dependencies
        run: yarn install

      - name: Build Docs
        run: yarn build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ORG_ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/
          cname: sublimetext.io
